name: AppScan CodeSweep

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run CodeSweep Scan
        uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v2
